---
.travis.yml:
  docker_sets:
  - set: docker/debian-8
  - set: docker/centos-7

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
    ':development':
      - gem: beaker-testmode_switcher
      - gem: beaker-rspec
      - gem: beaker-docker
      #  workaround https://github.com/puppetlabs/beaker-puppet/pull/102/files
      - gem: beaker-puppet
        version: '~> 1.14.0'
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper

  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
